from PIL import Image
import os
import exifread
from datetime import datetime
from geopy.geocoders import Nominatim

def get_country_initials(latitude, longitude):
    geolocator = Nominatim(user_agent="photo_renamer")
    location = geolocator.reverse(f"{latitude}, {longitude}", exactly_one=True)
    country = location.raw['address']['country']
    country_initials = ''.join(word[0] for word in country.split())
    return country_initials

def rename_photos(folder_path):
    if not os.path.exists(folder_path):
        print("Le chemin spécifié n'existe pas.")
        return

    for filename in os.listdir(folder_path):
        if filename.endswith(".jpg") or filename.endswith(".jpeg") or filename.endswith(".png"):
            image_path = os.path.join(folder_path, filename)
            try:
                image = Image.open(image_path)
                tags = exifread.process_file(open(image_path, 'rb'))
                latitude = tags.get('GPS GPSLatitude').values
                longitude = tags.get('GPS GPSLongitude').values

                country_initials = get_country_initials(latitude, longitude)

                date_time = str(tags.get('EXIF DateTimeOriginal'))
                date_time_obj = datetime.strptime(date_time, '%Y:%m:%d %H:%M:%S')
                formatted_date_time = date_time_obj.strftime('%Y%m%d_%H%M%S')

                new_filename = f"{country_initials}_{formatted_date_time}.jpg"

                os.rename(image_path, os.path.join(folder_path, new_filename))
                print(f"{filename} a été renommé en {new_filename}")
            except Exception as e:
                print(f"Erreur lors du traitement de {filename}: {e}")

folder_path = "/chemin/vers/votre/dossier"
rename_photos(folder_path)
